### ISSUE TITLE
TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by treb0r** [philhawksworth/shopify-11ty#2]
I decided to try this out on my local development machine and hit this error.

Is the demo shop still available in Shopify?

```
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/home/rob/Eleventy/shopify-11ty/node_modules/node-fetch/lib/index.js:1327:9)
    at /home/rob/Eleventy/shopify-11ty/node_modules/node-fetch/lib/index.js:1440:19
    at new Promise (<anonymous>)
    at fetch (/home/rob/Eleventy/shopify-11ty/node_modules/node-fetch/lib/index.js:1437:9)
    at exports.postToShopify (/home/rob/Eleventy/shopify-11ty/netlify/functions/utils/postToShopify.js:7:26)
    at module.exports (/home/rob/Eleventy/shopify-11ty/src/site/_data/products.js:5:26)
    at TemplateData.getDataValue (/home/rob/Eleventy/shopify-11ty/node_modules/@11ty/eleventy/src/TemplateData.js:385:29)
    at async TemplateData.getAllGlobalData (/home/rob/Eleventy/shopify-11ty/node_modules/@11ty/eleventy/src/TemplateData.js:228:18)
    at async TemplateData.getData (/home/rob/Eleventy/shopify-11ty/node_modules/@11ty/eleventy/src/TemplateData.js:255:24)
> Cannot read properties of undefined (reading 'products')

`TypeError` was thrown:
    TypeError: Cannot read properties of undefined (reading 'products')
        at module.exports (/home/rob/Eleventy/shopify-11ty/src/site/_data/products.js:54:19)
        at async TemplateData.getDataValue (/home/rob/Eleventy/shopify-11ty/node_modules/@11ty/eleventy/src/TemplateData.js:385:23)
        at async TemplateData.getAllGlobalData (/home/rob/Eleventy/shopify-11ty/node_modules/@11ty/eleventy/src/TemplateData.js:228:18)
        at async TemplateData.getData (/home/rob/Eleventy/shopify-11ty/node_modules/@11ty/eleventy/src/TemplateData.js:255:24)
```

**Comment by treb0r** [comment]
I realised the that the environment variables were not available to the development environment. I used the netlify-cli tool to add them and now it works. Thanks!
