### ISSUE TITLE
Cart function is crashing on demo for this project

### ISSUE THREAD

**Issue by gammacray** [philhawksworth/shopify-11ty#3]
Hey folks. I was just poking around the demo build of this at https://shopify-11ty.netlify.app and I note that adding a product to cart crashes the cart routine you've built for it. Guessing the API has changed since this article was written. Thought I'd give you a heads up.

```
An unhandled error in the function code triggered the following message:

FetchError - invalid json response body at https://shopify-11ty.netlify.app/api/get-cart reason: Unexpected end of JSON input

Stack trace
FetchError: invalid json response body at https://shopify-11ty.netlify.app/api/get-cart reason: Unexpected end of JSON input
    at /var/task/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Runtime.exports.handler (/var/task/netlify/functions/cart-view.js:9:18)
Connection details
Netlify internal ID: 01GFMNG1H6HGG2EWX926RTM14D
```

Sweet project! I wanna take 11ty for a spin building a Shopify storefront. Thanks for this.

**Comment by tomreinert** [comment]
+1 on this issue. 

Any hints on how to fix this?

**Comment by unclehowell** [comment]
This works https://github.com/lazavazav/cart
